#!/bin/bash
ipfs init

sleep 5

nohup ipfs daemon &

sleep 5

ipfs id

sleep 10

# Add any existing data. Help speed up startup.
ipfs add -r /home/safeuser/koa-ipfs-blog/ipfs-data

sleep 5

# Copy the config file
#cp /home/safeuser/koa-ipfs-blog/ipfs-config/common.js /home/safeuser/koa-ipfs-blog/config/env/

export KOA_ENV=production
npm start
